canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-diagnose
name: MII_IG_Diagnose
status: active
version: 2025.0.1
packageId: de.medizininformatikinitiative.kerndatensatz.diagnose
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  de.basisprofil.r4: 1.5.x
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.x
  kbv.all.st: 1.27.0

extension:
  - url: https://www.medizininformatik-initiative.de/fhir/modul-meta/StructureDefinition/mii-ex-meta-license-codeable
    valueCodeableConcept:
      coding:
        - system: http://spdx.org/licenses/
          code: CC-BY-4.0
          display: Creative Commons Attribution 4.0 International License

menu:
  Home: index.html
  Artifacts: artifacts.html