canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-diagnose-de-2
name: MII_IG_Diagnose_DE
status: active
version: "2.0.0-alpha3"
packageId: de.medizininformatikinitiative.kerndatensatz.diagnose
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  de.basisprofil.r4: 1.4.0
  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
